service:
  name: udagram

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  profile: udagramdevdjs
  region: us-east-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
